// notices writes THIRD_PARTY_NOTICES.md: the license of every module
// linked into the QR example or the browser demo, read from the module
// cache, so that what the binaries carry is what they credit.
//
//	go run ./internal/tools/notices > THIRD_PARTY_NOTICES.md
package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type module struct {
	path, version, dir string
}

var licenseName = regexp.MustCompile(`(?i)^(LICENSE|LICENCE|COPYING|NOTICE)(\.(txt|md|rst))?$`)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "notices:", err)
		os.Exit(1)
	}
}

func run() error {
	modules := map[string]module{}
	// The native binary, and the browser app with its own module.
	for _, build := range []struct {
		dir  string
		env  []string
		pkgs string
	}{
		{".", nil, "./examples/qrcode"},
		{".", []string{"GOOS=js", "GOARCH=wasm", "GOWORK=" + mustWorkspace()}, "./examples/qrcode"},
	} {
		cmd := exec.Command("go", "list", "-deps", "-f", `{{with .Module}}{{.Path}}	{{.Version}}	{{.Dir}}{{end}}`, build.pkgs)
		cmd.Dir, cmd.Env = build.dir, append(os.Environ(), build.env...)
		out, err := cmd.Output()
		if err != nil {
			return fmt.Errorf("go list in %s: %w", build.dir, err)
		}
		for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
			fields := strings.Split(line, "\t")
			if len(fields) != 3 || fields[2] == "" || strings.HasPrefix(fields[0], "nimbleterminal.dev/ntqrcode") {
				continue
			}
			if _, seen := modules[fields[0]]; !seen {
				modules[fields[0]] = module{fields[0], fields[1], fields[2]}
			}
		}
	}
	var paths []string
	for p := range modules {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var b bytes.Buffer
	b.WriteString(`# Third-party notices

ntqrcode is MIT licensed; see LICENSE.txt. The native and WASM demos
link the dependencies below. Generated by internal/tools/notices.

`)

	// The Go runtime and standard library are compiled into every binary.
	goroot, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		return err
	}
	text, err := goLicense(strings.TrimSpace(string(goroot)))
	if err != nil {
		return err
	}
	section(&b, "The Go runtime and standard library", "https://go.dev", text)
	var missing []string
	for _, p := range paths {
		m := modules[p]
		entries, err := os.ReadDir(m.dir)
		if err != nil {
			return fmt.Errorf("%s: %w", p, err)
		}
		var texts [][]byte
		for _, e := range entries {
			if !e.IsDir() && licenseName.MatchString(e.Name()) {
				text, err := os.ReadFile(filepath.Join(m.dir, e.Name()))
				if err != nil {
					return err
				}
				texts = append(texts, text)
			}
		}
		if len(texts) == 0 {
			missing = append(missing, p)
			continue
		}
		section(&b, m.path+" "+m.version, "", bytes.Join(texts, []byte("\n\n")))
	}
	if len(missing) > 0 {
		return fmt.Errorf("no license file in: %s", strings.Join(missing, ", "))
	}
	_, err = os.Stdout.Write(append(bytes.TrimRight(b.Bytes(), "\n"), '\n'))
	return err
}

// Homebrew keeps Go in libexec and its license in the enclosing keg.
func goLicense(root string) ([]byte, error) {
	root = filepath.Clean(root)
	name := filepath.Join(root, "LICENSE")
	text, err := os.ReadFile(name)
	if os.IsNotExist(err) && filepath.Base(root) == "libexec" {
		parent := filepath.Join(filepath.Dir(root), "LICENSE")
		text, err = os.ReadFile(parent)
		if err != nil {
			return nil, fmt.Errorf("runtime license for Go (checked %s and %s): %w", name, parent, err)
		}
	}
	if err != nil {
		return nil, fmt.Errorf("runtime license for Go %s: %w", name, err)
	}
	return text, nil
}

func section(b *bytes.Buffer, title, note string, text []byte) {
	fmt.Fprintf(b, "## %s\n\n", title)
	if note != "" {
		fmt.Fprintf(b, "%s\n\n", note)
	}
	b.WriteString("```\n")
	b.Write(bytes.TrimRight(text, "\n"))
	b.WriteString("\n```\n\n")
}

func mustWorkspace() string {
	p, err := filepath.Abs("wasm.work")
	if err != nil {
		panic(err)
	}
	return p
}
